name: Sync Fork

on:
  schedule:
    - cron: '0 13 * * 3'  # Rulează în fiecare miercuri la ora 13:00 UTC
  workflow_dispatch:  # Permite rularea manuală a acțiunii

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add upstream and fetch changes
        run: |
          git remote add upstream https://github.com/willswire/unifi-ddns.git || true
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      - name: Push changes to fork
        run: |
          git push origin main || true
